FROM node:18-alpine

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile

COPY src/backend ./src/backend
COPY .env.vault ./

EXPOSE 8081

ENV NODE_ENV=production

CMD ["sh", "-c", "DOTENV_KEY=$(pnpx dotenv-vault keys production --yes) && node ./src/backend/server.mjs"]
